services:
  _defaults:
    autowire: false
    autoconfigure: false
    bind:
      $projectDir: '%kernel.project_dir%'

  Drinksco\ConsoleUiBundle\Controller\AppController:
    class: Drinksco\ConsoleUiBundle\Controller\AppController
    public: true
    arguments:
      $kernel: '@kernel'
      $template: '@twig'
    tags: [ 'controller.service_arguments' ]

  Drinksco\ConsoleUiBundle\Controller\CommandScheduleController:
    class: Drinksco\ConsoleUiBundle\Controller\CommandScheduleController
    arguments:
      $handler: '@Drinksco\ConsoleUiBundle\Queue\QueueCommandHandler'
    tags: [ 'controller.service_arguments' ]

  Drinksco\ConsoleUiBundle\Queue\QueueCommandHandler:
    class: Drinksco\ConsoleUiBundle\Queue\QueueCommandHandler
    arguments:
      $eventDispatcher: '@event_dispatcher'
      $env: '%env(APP_ENV)%'

  Drinksco\ConsoleUiBundle\Queue\RunCommandProcessor:
    class: Drinksco\ConsoleUiBundle\Queue\RunCommandProcessor
    arguments:
      $hub: '@Symfony\Component\Mercure\HubInterface'
    tags:
      - { name: 'enqueue.client.processor', topicName: 'run_command' }